name: Upload Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.11"

      - name: Install tools
        run: python -m pip install build toml requests

      - name: Read version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Check if version exists on PyPI
        run: |
          EXISTS=$(curl -s https://pypi.org/pypi/thinagents/json | jq -r ".releases | has(\"$VERSION\")")
          if [ "$EXISTS" == "true" ]; then
            echo "Version $VERSION already exists on PyPI. Skipping publish."
            exit 1
          fi

      - name: Clean old builds
        run: rm -rf dist/ build/ *.egg-info

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
